[package]
name = "quiz11"
version = "0.1.0"
edition = "2024"

[dependencies]
book = { path = "../../../../../crypto-n-rust/src/libs/book" }
quizzes = { path = "../../.." }
libs = { path = "../../../../libs" }

tokio = { version = "1.53.1", features = ["full"] }
teloxide = { version = "0.17.0", features = ["macros"] }
reqwest = { version = "0.13.4", features = ["json"] }
serde_json = "1.0.151"
csv        = "1.0"
serde      = { version = "1.0", features = ["derive"] }
serde_with = "3.21.0"
clap       = { version = "4.6.4", features = ["derive"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

