[package]
name = "libs"
version = "0.1.0"
edition = "2024"

[lib]
name = "libs"
path = "src/lib.rs"

[dependencies]
rand = "0.10.2"
chrono = "0.4.45"
csv = "1.0"
paste = "1.0"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_with = "3.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
toml = "1.1.4"
ethers = { version = "2.0.14", default-features = false, features = ["rustls"] }
rpassword = "7.5.4"

book = { path = "../../crypto-n-rust/src/libs/book" }

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(tarpaulin_include)']
