[env]
TEST_FILE = "data/sample_close_pivots.tsv"

[tasks.tests]
# Dependencies run sequentially in the exact order listed below
dependencies = ["test", "afterward"]

[tasks.coverage]
dependencies = ["tarpaulin", "afterward"]

[tasks.afterward]
script = [ "head -n 2 ${TEST_FILE} | sponge ${TEST_FILE}" ]

