name: minimi_dusk

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-minimi-dusk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pivoteur.github.io
        uses: actions/checkout@v4

      - name: Checkout protocol
        uses: actions/checkout@v4
        with:
          repository: pivoteur/protocol
          path: protocol

      - name: Checkout crypto-n-rust
        uses: actions/checkout@v4
        with:
          repository: logicalgraphs/crypto-n-rust
          path: crypto-n-rust

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build minimi_dusk
        run: |
          cargo build --manifest-path protocol/dapps/minimi_dusk/Cargo.toml --bin minimi_dusk
          echo "$GITHUB_WORKSPACE/protocol/dapps/minimi_dusk/target/debug" >> $GITHUB_PATH

      - name: Putting date and URL into the env
        run: |
          echo "LE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "PIVOT_URL=https://raw.githubusercontent.com/pivoteur/pivoteur.github.io" >> $GITHUB_ENV

      - name: Run minimi_dusk
        env:
          PIVOTEUR_TOKEN: ${{ secrets.PIVOTEUR_TOKEN }}
        run: |
          minimi_dusk pivot $LE_DATE --min
