name: Run assets

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout protocol # Repository A
        uses: actions/checkout@v4
        with: 
          path: protocol

      - name: Set up rust
        uses: dtolnay/rust-toolchain@stable
          
      - name: Checkout crypto-n-rust # Repository B
        uses: actions/checkout@v4
        with:
          repository: logicalgraphs/crypto-n-rust
          token: ${{ secrets.PIVOT_GIT_TOKEN }}
          path: crypto-n-rust  # Repository B for `book` dependencies

      - name: Build assets
        run: |
          cargo build --manifest-path protocol/dapps/assets/Cargo.toml --bin assets
          echo "$GITHUB_WORKSPACE/protocol/dapps/assets/target/debug" >> $GITHUB_PATH

      - name: Checkout pivoteur.github.io # Repository C
        uses: actions/checkout@v4
        with:
          repository: pivoteur/pivoteur.github.io
          token: ${{ secrets.PIVOTEUR_TOKEN }}
          path: pivoteur.github.io # assets will read/write here

      - name: Putting date into the env
        run: |
          echo "LE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: run assets and Log Output
        run: |
          assets pivot $LE_DATE >> pivoteur.github.io/data/assets.tsv

      - name: Commit and push results to pivoteur.github.io
        env: 
          USER0_NAME: ${{ vars.USER0_NAME }}
          USER0_EMAIL: ${{ secrets.USER0_EMAIL }}
        run: |
          cd pivoteur.github.io
          git config --local user.name "$USER0_NAME"
          git config --local user.email "$USER0_EMAIL"
          git add data/assets.tsv
          git diff --staged --quiet && echo "Nothing to commit, skipping push" && exit 0
          git commit -m "assets $LE_DATE"
          git push

