name: Run virtsz

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-virtsz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout protocol # Repository A
        uses: actions/checkout@v4
        with: 
          path: protocol

      - name: Set up rust
        uses: dtolnay/rust-toolchain@stable
          
      - name: Checkout crypto-n-rust # Repository B
        uses: actions/checkout@v4
        with:
          repository: logicalgraphs/crypto-n-rust
          token: ${{ secrets.PIVOT_GIT_TOKEN }}
          path: crypto-n-rust  # Repository C for `book` dependancies

      - name: Build virtsz 
        run: cargo build --manifest-path protocol/dapps/virtsz/Cargo.toml --bin virtsz 

      - name: Checkout pivoteur.github.io # Repository B
        uses: actions/checkout@v4
        with:
          repository: pivoteur/pivoteur.github.io
          token: ${{ secrets.PIVOTEUR_TOKEN }}
          path: pivoteur.github.io # virtsz will read/write here

      - name: Putting date into the env
        run: |
          echo "LE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "PATH=protocol/dapps/virtsz/target/debug:$PATH" >> $GITHUB_ENV
          echo "PIVOT_URL=https://raw.githubusercontent.com/pivoteur/pivoteur.github.io" >> $GITHUB_ENV

      - name: Run virtsz
        run: |
          echo "current dir has the following"
          ls -l
          find . -name virtsz
          sh ./protocol/scripts/auto-virtsz.sh pivoteur.github.io/data/pivots/open/raw

      - name: Commit and push results to pivoteur.github.io
        env: 
          USER1_NAME: ${{ vars.USER1_NAME }}
          USER1_EMAIL: ${{ secrets.USER1_EMAIL }}
          PAT: ${{ secrets.PIVOTEUR_TOKEN }}
        run: |
          cd pivoteur.github.io
          git config user.name "$USER1_NAME"
          git config user.email "$USER1_EMAIL"
          git remote set-url origin https://x-access-token:$PAT@github.com/pivoteur/pivoteur.github.io
          git add data/pivots/open/raw/*.tsv
          git status
          ls -l data/pivots/open/raw/*.tsv
          git commit -m "virtsz $LE_DATE"
          git push
